name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1  # Add your cluster name here.
  GKE_ZONE: us-west1-a  # Add your cluster zone here.
  DEPLOYMENT_NAME: ai-collaborator-agent-gke-deploy # Add your deployment name here.
  IMAGE: ai-collaborator-agent # Image Name

jobs:
  setup-build-publish-deploy:
    name: Setup, Setup Secrets, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Get the GKE credentials so we can deploy to the cluster
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker


    - name: Setup Secrets
      env:
        # Map GitHub Secrets to environment variables
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
        DATABRICKS_WAREHOUSE_HTTP_PATH: ${{secrets.DATABRICKS_WAREHOUSE_HTTP_PATH}}
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
        FRONTEND_ORIGIN: ${{secrets.FRONTEND_ORIGIN}}
        FRONTEND_ORIGIN_DEV: ${{secrets.FRONTEND_ORIGIN_DEV}}
        OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

      run: |
        kubectl create secret generic my-app-secrets \
          --from-literal=DATABRICKS_TOKEN="${DATABRICKS_TOKEN}" \
          --from-literal=DATABRICKS_WAREHOUSE_HTTP_PATH="${DATABRICKS_WAREHOUSE_HTTP_PATH}" \
          --from-literal=DATABRICKS_HOST="${DATABRICKS_HOST}" \
          --from-literal=CLERK_SECRET_KEY="${CLERK_SECRET_KEY}" \
          --from-literal=FRONTEND_ORIGIN="${FRONTEND_ORIGIN}" \
          --from-literal=FRONTEND_ORIGIN_DEV="${FRONTEND_ORIGIN_DEV}" \
          --from-literal=OPENAI_API_KEY="${OPENAI_API_KEY}" \
          --dry-run=client -o yaml | kubectl apply -f -
          
    # Build the Docker image

    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
